import {
  LayoutDashboard,
  User,
  FileText,
  Sparkles,
  FolderKanban,
  ClipboardList,
  Code2,
  HelpCircle,
  Bot,
  BarChart3,
  Settings,
  Menu,
  Sun,
  Moon,
  ChevronLeft,
  ChevronRight,
  Monitor,
  AlertTriangle,
  CheckCircle2,
  Info,
  X,
  Loader2,
  LogOut,
  Building,
  Briefcase,
  Trash2,
  Plus,
  Eye,
  Download,
  Upload,
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Profile: User,
  Resume: FileText,
  ATS: Sparkles,
  Portfolio: FolderKanban,
  Projects: ClipboardList,
  DSA: Code2,
  Interview: HelpCircle,
  AI: Bot,
  Analytics: BarChart3,
  Settings: Settings,
  Menu: Menu,
  Sun: Sun,
  Moon: Moon,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Monitor: Monitor,
  Warning: AlertTriangle,
  Success: CheckCircle2,
  Info: Info,
  Close: X,
  Spinner: Loader2,
  Logout: LogOut,
  School: Building,
  Job: Briefcase,
  Delete: Trash2,
  Add: Plus,
  View: Eye,
  Download: Download,
  Upload: Upload,
};

export type IconType = keyof typeof Icons;
